# Theme settings
doks:
    baseurl:
    color_theme:
    header:
        logo:
            text: Auto Scaling en Amazon Web Services
            image:
        nav:
            - item_name: Introducción a AWS
              item_url: '/'
            - item_name: Demo 1
              item_url: '#'
            - item_name: Demo 2
              item_url: '#'
    footer:
        content:
            logo:
                text: Auto Scaling en Amazon Web Services
                image:
            copyright: Copyright &copy; 2018. - Auto Scaling en Amazon Web Services <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: https://twitter.com/charliesanch3z
            - network_name: linkedin
              profile_url: https://www.linkedin.com/in/charliejsanchez/
            - network_name: github
              profile_url: https://github.com/carlosjsanch3z
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
